adnat-backend/config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  get 'sign_up/index'
  get 'login/index'

  resources :users
  resources :organisations
  resources :employees
  resources :shifts

  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  root 'organisations#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

adnat-backend/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

adnat-backend/app/models/employee.rb
class Employee < ApplicationRecord
end

adnat-backend/app/models/organisation.rb
class Organisation < ApplicationRecord
end

adnat-backend/app/models/shift.rb
class Shift < ApplicationRecord
end

adnat-backend/app/models/user.rb
require 'bcrypt'

class EmailValidator < ActiveModel::EachValidator

  include BCrypt

  def validate_each(record, attribute, value)
    unless value =~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
      record.errors[attribute] << (options[:message] || "is not a valid email")
    end
  end
end

class UserValidator < ActiveModel::Validator
   def validate(record)
      # password hashing
        @password = BCrypt::Password.create(record[:password])
        record[:password] = @password
   end
end

class User < ApplicationRecord
    has_secure_password
    validates :first_name, presence: true, length: {minimum: 2}
    validates :last_name, presence: true, length: {minimum: 2}
    validates :email, presence: true, email: true
    validates_confirmation_of :password,:password_confirmation, message: "The passwords do not match"
    # validates_presence_of :password_confirmation, :if => :password_changed?
    validates_with UserValidator
end

adnat-backend/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user

    def current_user
        if session[:id]
        puts session[:id]
        @user = User.find(session[:id])
        byebug
        @current_user ||= User.find(session[:id])
        puts @current_user
        return @current_user
        else
        @current_user = nil
        end
    end

end

adnat-backend/app/controllers/login_controller.rb
class LoginController < ApplicationController
  def index
  end
end

adnat-backend/app/controllers/organisations_controller.rb
class OrganisationsController < ApplicationController
    def index
        @organisation = Organisation.all
    end

    def show
        redirect_to action:"index"
    end

    def new
        @organisation = Organisation.new
    end

    def edit
        @organisation = Organisation.find(params[:id])
    end

    def create
        @organisation = Organisation.new(orgs_params)

        if @organisation.save
            redirect_to @organisation
        else
            render 'new'
        end
    end

    def update
        @organisation = Organisation.find(params[:id])
        if @organisation.update(orgs_params)
            redirect_to @organisation
        else
            render 'edit'
        end
    end

    def destroy
        @organisation = Organisation.find(params[:id])
        @organisation.destroy

        redirect_to organisations_path
    end

    private
     def orgs_params
        params.require(:organisation).permit(:org_name,:hourly_rate)
     end
end

adnat-backend/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
    byebug
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:id] = user.id
      redirect_to root_url, notice: "Logged in!"
    else
      flash.now[:alert] = "Email or password is invalid"
      render "new"
    end
  end
  def destroy
    session[:id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
end

adnat-backend/app/controllers/users_controller.rb
class UsersController < ApplicationController

    def index
        @users = User.all
    end

    def show
        @user = User.find(params[:id])
    end

    def new
        @user = User.new
    end

    def edit
        @user = User.find(params[:id])
    end

    def create
        @user = User.new(user_params)

        if @user.save
            redirect_to @user
        else
            render 'new'
        end
    end

    def update
        @user = User.find(params[:id])
        if @user.update(user_params)
            redirect_to @user
        else
            render 'edit'
        end
    end

    def destroy
        @user = User.find(params[:id])
        @user.destroy
 
        redirect_to users_path
    end

    private
     def user_params
        params.require(:user).permit(:first_name,:last_name,:email_address,:password)
     end
end

adnat-backend/app/helpers/application_helper.rb
module ApplicationHelper
end

adnat-backend/app/helpers/login_helper.rb
module LoginHelper
end

adnat-backend/app/helpers/organisations_helper.rb
module OrganisationsHelper
end

adnat-backend/app/helpers/sessions_helper.rb
module SessionsHelper
end

adnat-backend/app/helpers/users_helper.rb
module UsersHelper
end

adnat-backend/app/views/common/_header.html.erb
<div>
  <div class="adnatHeader">
    <h1>ADNAT</h1>
  </div>
</div>

adnat-backend/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AdnatBackend</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

adnat-backend/app/views/login/index.html.erb
<div class="adnatHeader">
  <h1>ADNAT</h1>
</div>
<div class="adnatPageHeader">
    <h2>Login</h2>
</div>
<div>
  <form id="adnatLoginForm">
    <div class="adnatLoginInputBlock">
      <label for="adnatLoginEmail">Email: </label>
      <input type="text" name="email" id="adnatLoginEmail" required>
    </div>
    <div class="adnatLoginInputBlock">
      <label for="adnatLoginPassword">Password: </label>
      <input type="text" name="email" id="adnatLoginPassword" required>
    </div>
    <div class="adnatLoginInputBlock">
      <input type="checkbox" name="email" id="adnatLoginRememberMe" required>
      <label for="adnatLoginRememberMe">remember me </label>
    </div>
    <div class="adnatLoginInputBlock" id="adnatLoginButton">
      <input type="submit" value="Log In">
    </div>
    <%= link_to 'Sign Up', controller: 'users', action: 'new' %>
    <div><a href="#">Forgot your Password?</a></div>
  </form>

adnat-backend/app/views/organisations/_form.html.erb
<%= form_with scope: :organisation, local: true do |form| %>
    <p>
    <%= form.label :org_name %>
    <%= form.text_field :org_name %>
    </p>
 
    <p>
    <%= form.label :hourly_rate %>
    <%= form.text_field :hourly_rate %>
    </p>

    <p>
    <%= form.submit %>
    </p>
<% end %>

adnat-backend/app/views/organisations/edit.html.erb
<%= render 'common/header' %>
<h1>Edit Organisation</h1>

<%= form_with(model: @organisation, local: true) do |form| %>
    <p>
    <%= form.label :org_name %>
    <%= form.text_field :org_name %>
    </p>
 
    <p>
    <%= form.label :hourly_rate %>
    <%= form.text_field :hourly_rate %>
    </p>

    <p>
    <%= form.submit %>
    </p>
<% end %>


<div><%= link_to 'Delete', organisation_path(@organisation),
      method: :delete,
      data: {confirm: 'are you sure?'} =%><div>
<div><%= link_to 'Back', organisation_path %></div>

adnat-backend/app/views/organisations/index.html.erb
<%= render 'common/header' %>

<% if current_user %>
  Logged in as <%= current_user[:email] %>.
  <%= link_to “Log Out”, logout_path %>
<% end %>
<div>

  <p>You are not the member of any organisations.<br>
    Join an existing one or create a new one</p>
</div>

<div>
  <h1>Organisations</h1>
  <table>
    <% @organisation.each do |org| %>
    <tr>
      <td><%=org.org_name =%></td>
      <td><%=org.hourly_rate =%></td>
      <td><%= link_to 'Edit', edit_organisation_path(org) =%></td>
      <td><%= link_to 'Delete', organisation_path(org),
      method: :delete,
      data: {confirm: 'are you sure?'} =%></td>
    </tr>
    <% end %>
  </table>
</div>


<div>
    <h1>Create Organisation</h1>
    <%= render 'form' %>
</div>

adnat-backend/app/views/organisations/show.html.erb
<p>
  <strong>Organisation Name:</strong>
  <%= @organisation.org_name %>
</p>
<p>
  <strong>Hourly Rate:</strong>
  <%= @organisation.hourly_rate %>
</p>

<%= link_to 'Edit', organisations_path(@organisation) %>
<%= link_to 'Back', organisations_path %>

adnat-backend/app/views/users/_form.html.erb
<%= form_with model: @user,  local: true do |form| %>

<% if @user.errors.any? %>
<div id="adnatSignInPageErrors">
    <h2>
        <%= pluralize(@user.errors.count, "error") %> prohibited
        this user from being saved:
    </h2>
    <ul>
        <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
    </ul>
</div>
<%end%>
<p>
    <%= form.label :first_name %><br>
    <%= form.text_field :first_name %>
</p>
<p>
    <%= form.label :last_name %><br>
    <%= form.text_field :last_name %>
</p>
<p>
    <%= form.label :email %><br>
    <%= form.text_field :email %>
</p>
<p>
    <%= form.label :password %>
    <br>
    <p>(6 Characters minimum)</p>
    
    
    <%= password_field(:user, :password, onchange: "if(document.getElementById('user_password').value.length < 6){alert('Your password needs to be at least 6 characters!');};") %>
</p>
<p>
    <%= form.label :password_confirmation, 'Password Confirmation' %><br>
    <%= password_field(:user, :password_confirmation, size: 20,onchange: "if(document.getElementById('user_password').value.length < 6){alert('Your password needs to be at least 6 characters!');};") %>
</p>
<p>
    <%= form.submit %>
</p>
<% end %>

adnat-backend/app/views/users/edit.html.erb
<%= render 'common/header' %>

<h1>Edit User</h1>

<%= render 'form' %>
<%= link_to 'Back', users_path %>

adnat-backend/app/views/users/index.html.erb
<%= render 'common/header' %>
<h1>Listing users</h1>
<table>
  <tr>
    <th>First Name</th>
    <th>Last Name</th>
    <th></th>
  </tr>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.first_name %></td>
      <td><%= user.last_name %></td>
      <td><%= user.email %></td>
      <td><%= link_to 'Show', user_path(user) %></td>
      <td><%= link_to 'Edit', edit_user_path(user) %></td>
      <td><%= link_to 'Delete', user_path(user),
      method: :delete,
      data: {confirm: 'are you sure?'} %></td>
    </tr>
  <% end %>
</table>

adnat-backend/app/views/users/new.html.erb
<%= render 'common/header' %>

<div class="adnatPageHeader">
    <h2>Sign Up</h2>
</div>
<div>
   <%= render 'form' %>
   <%= link_to 'Log In', controller: 'login' %>

adnat-backend/app/views/users/show.html.erb
<%= render 'common/header' %>
<p>
  <strong>First Name:</strong>
  <%= @user.first_name %>
</p>
<p>
  <strong>Last Name:</strong>
  <%= @user.last_name %>
</p>
<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>
<%= link_to 'Edit', users_path(@user) %>
<%= link_to 'Back', users_path %>